export const DEFAULT_CONTENT = {
  _id: 'site',
  brand: {
    name: 'مؤسسة الذهبية',
    tagline: 'أفضل معدات الصوت والدي جي الاحترافية لحفل زفافك. نوصل إحساس الموسيقى إلى كل ركن في القاعة.',
    logoText: 'مؤسسة الذهبية',
  },
  hero: {
    title: 'مؤسسة الذهبية',
    subtitle: 'أفضل معدات الصوت والدي جي الاحترافية لحفل زفافك',
    description: 'نوصل إحساس الموسيقى إلى كل ركن في القاعة',
    backgroundImage: 'https://images.unsplash.com/photo-1614886203666-c9d5cc572194?crop=entropy&cs=srgb&fm=jpg&q=85&w=2400',
    backgroundVideo: '',
    ctaPrimary: { label: 'اتصل الآن', href: 'tel:+966500000000' },
    ctaSecondary: { label: 'شاهد أعمالنا', href: '#gallery' },
    stats: [
      { value: '500+', label: 'حفل زفاف' },
      { value: '15+', label: 'سنة خبرة' },
      { value: '100%', label: 'رضا العملاء' },
      { value: '24/7', label: 'دعم متواصل' },
    ],
  },
  about: {
    title: 'من نحن',
    intro: 'مؤسسة الذهبية رائدة في تقديم خدمات الصوتيات والإضاءة والدي جي للحفلات الفاخرة في المملكة العربية السعودية. نمزج بين التقنية المتطورة والذوق الرفيع لنمنح مناسبتك تجربة لا تُنسى.',
    vision: 'أن نكون الخيار الأول والأفضل لكل حفل زفاف ومناسبة تبحث عن التميز، وأن نضع بصمة صوتية وبصرية تليق بأحلامك.',
    mission: 'نقدم أحدث أنظمة الصوت والإضاءة والمؤثرات بأيدي محترفين، مع اهتمام كامل بكل تفصيل ليكون حفلك مثالياً.',
    whyUs: [
      { icon: 'Award', title: 'خبرة تفوق 15 عاماً', desc: 'مئات الحفلات الناجحة تشهد بجودة خدماتنا.' },
      { icon: 'Speaker', title: 'أحدث المعدات العالمية', desc: 'ماركات عالمية موثوقة لصوت نقي وإضاءة مبهرة.' },
      { icon: 'Users', title: 'فريق محترف', desc: 'فنيون ومهندسون صوت ذوو خبرة عالية.' },
      { icon: 'Sparkles', title: 'لمسة ذهبية فاخرة', desc: 'كل تفصيلة مصممة لتترك انطباعاً استثنائياً.' },
    ],
    image: 'https://images.unsplash.com/photo-1544785349-c4a5301826fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600',
  },
  services: [
    { id: 's1', title: 'أنظمة الصوت الاحترافية', desc: 'أنظمة صوت متطورة عالية النقاء تغطي أي مساحة بجودة استوديو.', image: 'https://images.unsplash.com/photo-1534840641466-b1cdb8fb155e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Speaker', gallery: [] },
    { id: 's2', title: 'دي جي احترافي', desc: 'دي جيهات محترفون يقرأون الحدث ويشعلون الأجواء بأفضل الميكسات.', image: 'https://images.unsplash.com/photo-1648738673511-16dd92b30d3b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Disc3', gallery: [] },
    { id: 's3', title: 'حفلات الزفاف', desc: 'باقات متكاملة لحفلات زفاف لا تُنسى، صوت وإضاءة وتنسيق.', image: 'https://images.unsplash.com/photo-1717944097660-352ec0dc5c1f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Heart', gallery: [] },
    { id: 's4', title: 'حفلات التخرج', desc: 'اجعل تخرجك لحظة مبهرة بأجواء صوتية وضوئية استثنائية.', image: 'https://images.unsplash.com/photo-1501612780327-45045538702b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'GraduationCap', gallery: [] },
    { id: 's5', title: 'المؤتمرات', desc: 'حلول احترافية للمؤتمرات مع أنظمة ترجمة وميكروفونات لاسلكية.', image: 'https://images.unsplash.com/photo-1461784180009-21121b2f204c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Mic', gallery: [] },
    { id: 's6', title: 'الإضاءة الاحترافية', desc: 'إضاءة سينمائية ذكية تُحول أي قاعة إلى تحفة بصرية.', image: 'https://images.unsplash.com/photo-1573152958734-1922c188fba3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Lightbulb', gallery: [] },
    { id: 's7', title: 'المسرح', desc: 'مسارح كاملة الاستعداد بأحدث المعدات وأنظمة الصوت والإضاءة.', image: 'https://images.unsplash.com/photo-1558620013-a08999547a36?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Theater', gallery: [] },
    { id: 's8', title: 'الشاشات', desc: 'شاشات LED عملاقة وشاشات عرض عالية الوضوح لأي مناسبة.', image: 'https://images.unsplash.com/photo-1613093335399-829e30811789?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Monitor', gallery: [] },
    { id: 's9', title: 'المؤثرات الخاصة', desc: 'ثلج، ألعاب نارية باردة، دخان، ليزر ومؤثرات تسحر الحضور.', image: 'https://images.unsplash.com/photo-1509310202330-aec5af561c6b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200', icon: 'Sparkles', gallery: [] },
  ],
  gallery: [
    { id: 'g1', url: 'https://images.unsplash.com/photo-1614886203666-c9d5cc572194?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'زفاف' },
    { id: 'g2', url: 'https://images.unsplash.com/photo-1558620013-a08999547a36?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'مسرح' },
    { id: 'g3', url: 'https://images.unsplash.com/photo-1573152958734-1922c188fba3?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'إضاءة' },
    { id: 'g4', url: 'https://images.unsplash.com/photo-1613093335399-829e30811789?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'مسرح' },
    { id: 'g5', url: 'https://images.unsplash.com/photo-1544785349-c4a5301826fd?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'دي جي' },
    { id: 'g6', url: 'https://images.unsplash.com/photo-1648738673511-16dd92b30d3b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'دي جي' },
    { id: 'g7', url: 'https://images.unsplash.com/photo-1461784180009-21121b2f204c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'دي جي' },
    { id: 'g8', url: 'https://images.unsplash.com/photo-1534840641466-b1cdb8fb155e?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'صوت' },
    { id: 'g9', url: 'https://images.unsplash.com/photo-1618609377864-68609b857e90?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'صوت' },
    { id: 'g10', url: 'https://images.unsplash.com/photo-1509310202330-aec5af561c6b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'مؤثرات' },
    { id: 'g11', url: 'https://images.unsplash.com/photo-1501612780327-45045538702b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'مسرح' },
    { id: 'g12', url: 'https://images.unsplash.com/photo-1717944097660-352ec0dc5c1f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1400', category: 'زفاف' },
  ],
  videos: [
    { id: 'v1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: 'حفل زفاف فاخر', addedAt: Date.now() - 1000 },
    { id: 'v2', url: 'https://www.youtube.com/watch?v=9bZkp7q19f0', title: 'عرض إضاءة احترافي', addedAt: Date.now() - 2000 },
  ],
  youtubeSettings: {
    channelUrl: '',
    playlistUrl: '',
    autoSync: false,
    maxVideos: 12,
    columns: 3,
  },
  testimonials: [
    { id: 't1', name: 'أحمد الشمري', role: 'عريس', text: 'خدمة استثنائية بكل معنى الكلمة! جعلوا ليلة زفافي أسطورية.', rating: 5 },
    { id: 't2', name: 'سارة القحطاني', role: 'منظمة حفلات', text: 'أفضل شركة صوتيات وإضاءة تعاملت معها. احترافية عالية.', rating: 5 },
    { id: 't3', name: 'خالد العتيبي', role: 'رجل أعمال', text: 'نظموا لنا مؤتمراً ضخماً بأعلى مستوى. أنصح بهم بشدة.', rating: 5 },
  ],
  contact: {
    phone: '+966500000000',
    whatsapp: '9665XXXXXXXX', // ضع رقمك الحقيقي بصيغة دولية بدون + أو صفر
    email: 'info@alzahabiya.sa',
    address: 'الرياض، المملكة العربية السعودية',
    mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3625.353361897196!2d46.6752!3d24.7136!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjTCsDQyJzQ4LjkiTiA0NsKwNDAnMzAuNyJF!5e0!3m2!1sen!2ssa!4v1',
  },
  social: {
    instagram: 'https://instagram.com/',
    facebook: 'https://facebook.com/',
    tiktok: 'https://tiktok.com/',
    snapchat: 'https://snapchat.com/',
    youtube: 'https://youtube.com/',
    telegram: 'https://t.me/',
    twitter: '',
    linkedin: '',
  },
  seo: {
    title: 'مؤسسة الذهبية - أفضل معدات الصوت والدي جي',
    description: 'أفضل معدات الصوت والدي جي الاحترافية لحفل زفافك. نوصل إحساس الموسيقى إلى كل ركن في القاعة.',
    keywords: 'مؤسسة الذهبية, دي جي, صوت, حفلات زفاف, إضاءة, معدات صوتية, الرياض',
    ogTitle: 'مؤسسة الذهبية',
    ogDescription: 'أفضل معدات الصوت والدي جي الاحترافية',
    ogImage: '',
    googleAnalytics: '',
  },
  footer: {
    text: '© 2025 مؤسسة الذهبية. جميع الحقوق محفوظة.',
    tagline: 'نصنع لحظات لا تُنسى بلمسة ذهبية.',
  },
  theme: {
    primary: '#D4AF37',
    background: '#0F0F0F',
  },
};
